name: ESLint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    # - name: configure
    #   run: ./configure
    - name: npm install, build
      run: make install
    - name: ESLint
      run: make lint
